baseURL = "https://lokal.ninja/schweiz"
languageCode = "de-DE"
title = "Lokal Ninja - Schweiz"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Schweiz"
  repo = "schweiz"
